### ISSUE TITLE
`ConcurrentModificationException` in `MnCsv.dup`

### ISSUE THREAD

**Issue by yegor256** [yegor256/tojos#101]
```
Exception in thread "Thread-8" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1606)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1639)
	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1637)
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:520)
	at java.base/java.util.HashMap.putAll(HashMap.java:792)
	at com.yegor256.tojos.MnCsv.dup(MnCsv.java:188)
	at com.yegor256.tojos.MnCsv.write(MnCsv.java:137)
	at com.yegor256.tojos.MnPostponed.lambda$start$0(MnPostponed.java:138)
```

**Comment by bibonix** [comment]
I'm planning to work on this. Will investigate the race condition and attempt a fix.

**Comment by bibonix** [comment]
Submitted a PR with a reproducing test and fix: https://github.com/yegor256/tojos/pull/184

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.0`
