### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2

### ISSUE THREAD

**Issue by yegor256** [yegor256/tojos#89]
```
Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2
	at com.yegor256.tojos.MnCsv.write(MnCsv.java:153)
	at com.yegor256.tojos.MnPostponed.lambda$start$0(MnPostponed.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.2`
