### ISSUE TITLE
NoClassDefFoundError: javax/json/stream/JsonGenerationException

### ISSUE THREAD

**Issue by yegor256** [yegor256/tojos#94]
```
java.lang.NoClassDefFoundError: javax/json/stream/JsonGenerationException
        at org.glassfish.json.JsonWriterImpl.<init>(JsonWriterImpl.java:71)
        at org.glassfish.json.JsonWriterFactoryImpl.createWriter(JsonWriterFactoryImpl.java:69)
        at com.yegor256.tojos.MnJson.write(MnJson.java:146)
        at com.yegor256.tojos.MnPostponed.lambda$start$0(MnPostponed.java:138)
```

**Comment by ConstantTeen** [comment]
@yegor256 I've noticed that in [pom.xml](https://github.com/yegor256/tojos/blob/master/pom.xml) some of the dependencies (including `org.glassfish:javax.json`) are declared as **optional**. According to [maven docs](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html), these optional dependencies must be explicitly **re-declared** within a user's project if they need them; otherwise, they will not appear on the classpath during compilation. 
To reproduce the exception, it’s enough to simply not mention the `org.glassfish:javax.json` dependency together with `com.yegor256:tojos` in pom.xml of any project that uses `MnJson()`.

**Comment by yegor256** [comment]
@ConstantTeen good points, thanks!

**Comment by bibonix** [comment]
@yegor256 I am planning to work on this. Will trace the optional dependency problem in `pom.xml` (the `javax.json` API and the Glassfish runtime are both declared as `<optional>true</optional>`), reproduce the `NoClassDefFoundError` from a downstream consumer, and submit a fix.

**Comment by bibonix** [comment]
PR submitted: #195. All CI jobs are green; ready for review.

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.1`
